### ISSUE TITLE
Performance Tracking

### ISSUE THREAD

**Issue by baylorhenshaw** [MHStats/Meta#9]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/MHStats/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the other Issues to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

Both (Website & Plugin)

**Describe the feature**

A large focus of performance tracking. For example, tracking tps, mspt, cpu, memory, etc. In addition to this, tracking loaded chunks, entities, etc. would also be super useful. Tools like Analyse are focused on player tracking and trends, so this could be a great tool for performance tracking.

**How the feature is useful**

For server owners, having good performance data can tell them a lot about how their server/network scales.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by ReportCardsMC** [comment]
Great suggestion! We'll be able to implement these statistics to help out server creators :))

I'll keep this open to post updates on what we have done so far about this.
